package com.halcyon.recurix.handler;

public enum ConversationState {

    AWAITING_SUBSCRIPTION_NAME,
    AWAITING_SUBSCRIPTION_PRICE,
    AWAITING_SUBSCRIPTION_DATE,
    AWAITING_SUBSCRIPTION_CONFIRMATION,

    AWAITING_NEW_NAME,
    AWAITING_NEW_PRICE,
    AWAITING_NEW_DATE,
    AWAITING_NEW_CATEGORY,
    AWAITING_NEW_PERIOD_MONTHS
}
